apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web
  labels:
    app: eshop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
      - name: eshop-web
        image: whatthehackmsft/eshoponweb-kubernetes
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
        - name: ApplicationInsights__ConnectionString
          value: "<INSERT_APP_INSIGHTS_CONNECTIONSTRING>"
        - name: ConnectionStrings__CatalogConnection
          value: "Server=<INSERT_DB_SERVER_IP>;Integrated Security=false;User ID=sqladmin;Password=<INSERT_PASSWORD>;Initial Catalog=Microsoft.eShopOnWeb.CatalogDb;TrustServerCertificate=True"
        - name: ConnectionStrings__IdentityConnection
          value: "Server=<INSERT_DB_SERVER_IP>;Integrated Security=false;User ID=sqladmin;Password=<INSERT_PASSWORD>;Initial Catalog=Microsoft.eShopOnWeb.Identity;TrustServerCertificate=True"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-web
  labels:
    app: eshop-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: eshop-web